name: zodgame

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          pip3 install -r ./zodgame/requirements.txt

      - name: Run Script
        env:
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        run: |
          python3 ./zodgame/zodgame.py "${{ secrets.ZODGAME_COOKIE }}"

      - name: Keep workflow alive
        run: |
          sleep 300

      - name: DingTalk Notification
        if: always()
        env:
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        shell: bash
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            MESSAGE="🎉 GitHub Actions 工作流执行成功！工作流名称: zodgame"
          else
            MESSAGE="❌ GitHub Actions 工作流执行失败！工作流名称: zodgame"
          fi
          curl -X POST -H 'Content-Type: application/json' \
          -d "{
            \"msgtype\": \"text\",
            \"text\": {
              \"content\": \"$MESSAGE\"
            }
          }" $DINGTALK_WEBHOOK_URL
