name: zodgame

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          pip3 install -r ./zodgame/requirements.txt

      - name: Run Script
        env:
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        run: |
          python3 ./zodgame/zodgame.py "${{ secrets.ZODGAME_COOKIE }}"

      - name: Keep workflow alive
        uses: liskin/gh-workflow-keepalive@main
        with:
          # 必须添加以下参数（根据仓库文档要求）
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # 注入 GITHUB_TOKEN 权限
          timeout-minutes: 360  # 设置最大保活时间（单位：分钟）
          interval-seconds: 30  # 心跳间隔时间（单位：秒）
