name: zodgame

on:
  schedule:
  - cron: "0 0 * * *"
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip3 install -r ./zodgame/requirements.txt
    - name: Run 
      run: |
        python3 ./zodgame/zodgame.py "${{secrets.ZODGAME_COOKIE}}"
    - uses: gautamkrishnar/keepalive-workflow@master
jobs:
  run_zodgame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZodGame Script
        env:
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}  # 注入环境变量
        run: |
          python zodgame.py "${{ secrets.COOKIE_STRING }}"
